{
  "openapi": "3.0.2",
  "info": {
    "title": "カラーミーショップ API",
    "description": "# カラーミーショップ API\n\n## 利用手順\n\n### OAuthアプリケーションの登録\n\nデベロッパーアカウントをお持ちでない場合は作成します。[デベロッパー登録ページ](https://api.shop-pro.jp/developers/sign_up)から登録してください。\n\n次に、[登録ページ](https://api.shop-pro.jp/oauth/applications/new)からアプリ登録を行ってください。\nスマートフォンのWebViewを利用する場合は、リダイレクトURIに`urn:ietf:wg:oauth:2.0:oob`を入力してください。\n\n### 認可\n\nカラーミーショップアカウントの認証ページを開きます。認証ページのURLは、`https://api.shop-pro.jp/oauth/authorize`に必要なパラメータをつけたものです。\n\n|パラメータ名|値|\n|---|---|\n|`client_id`|アプリ詳細画面で確認できるクライアントID|\n|`resp[...]",
    "termsOfService": "https://api.shop-pro.jp/developers/tos",
    "contact": {
      "name": "お問い合せ窓口",
      "url": "https://developer.shop-pro.jp"
    },
    "version": "1.0.0",
    "x-logo": {
      "url": "https://static-www.shop-pro.jp/img/cms_components/cms_header/cms_header_brand.svg"
    }
  },
  "servers": [
    {
      "url": "https://api.shop-pro.jp"
    }
  ],
  "tags": [
    {
      "name": "shop",
      "description": "ショップ",
      "x-displayName": "ショップ"
    },
    {
      "name": "sale",
      "description": "受注",
      "x-displayName": "受注"
    },
    {
      "name": "customer",
      "description": "顧客",
      "x-displayName": "顧客"
    },
    {
      "name": "product",
      "description": "商品",
      "x-displayName": "商品"
    },
    {
      "name": "stock",
      "description": "在庫",
      "x-displayName": "在庫"
    },
    {
      "name": "group",
      "description": "商品グループ",
      "x-displayName": "商品グループ"
    },
    {
      "name": "category",
      "description": "商品カテゴリー",
      "x-displayName": "商品カテゴリー"
    },
    {
      "name": "payment",
      "description": "決済",
      "x-displayName": "決済"
    },
    {
      "name": "delivery",
      "description": "配送",
      "x-displayName": "配送"
    },
    {
      "name": "gift",
      "description": "ギフト",
      "x-displayName": "ギフト"
    },
    {
      "name": "shop_coupon",
      "description": "ショップクーポン",
      "x-displayName": "ショップクーポン"
    }
  ],
  "paths": {
    "/v1/shop": {
      "get": {
        "summary": "ショップ情報の取得",
        "description": "ショップ名などの基本的な情報を取得することができるAPIです。\n",
        "operationId": "getShop",
        "tags": [
          "shop"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/sales": {
      "get": {
        "summary": "受注データのリストを取得",
        "description": "受注データのリストを取得します。（日付が指定されていない場合は直近1週間分を取得します。）",
        "operationId": "getSales",
        "tags": [
          "sale"
        ],
        "security": [
          {
            "OAuth2": [
              "read_sales"
            ]
          }
        ]
      },
      "post": {
        "summary": "受注データを作成",
        "description": "受注データを作成します。\n\nカラーミーショップでご契約中のプランがプレミアムのアカウントでのみご利用いただけます。\n\nリクエストボディ中の顧客情報をもとにゲスト購入として受注データを作成します。決済方法としては代金引換と銀行振込、ゆうちょ振替だけ指定できます。クエリパラメータで在庫を引き当てないように指定できます。\n\nwrite_salesスコープが必要です。\n",
        "operationId": "createSale",
        "tags": [
          "sale"
        ]
      }
    },
    "/v1/sales/stat": {
      "get": {
        "summary": "売上集計の取得",
        "description": "",
        "operationId": "statSale",
        "tags": [
          "sale"
        ],
        "security": [
          {
            "OAuth2": [
              "read_sales"
            ]
          }
        ]
      }
    },
    "/v1/sales/{sale_id}": {
      "get": {
        "summary": "受注データの取得",
        "description": "",
        "operationId": "getSale",
        "tags": [
          "sale"
        ],
        "security": [
          {
            "OAuth2": [
              "read_sales"
            ]
          }
        ]
      },
      "put": {
        "summary": "受注データの更新",
        "description": "該当受注の決済がAmazon Pay、LINE Pay、または楽天ペイ（オンライン決済）である場合は、熨斗・メッセージカード・ラッピングの手数料を更新すると、決済金額が自動的に購入者に請求もしくは返金されます。\n\nただし、LINE Payの場合は、決済金額の変更は減額のみ行うことができます。\n",
        "operationId": "updateSale",
        "tags": [
          "sale"
        ],
        "security": [
          {
            "OAuth2": [
              "write_sales"
            ]
          }
        ]
      }
    },
    "/v1/sales/{sale_id}/cancel": {
      "put": {
        "summary": "受注のキャンセル",
        "description": "受注をキャンセルすると、以下のことが起こります。\n\n- 該当受注の商品購入数が0になる\n- 該当受注の合計金額が0になる\n- 該当受注の`canceled`が`true`になる\n- 該当受注に使用されたショップポイント・GMOポイントがキャンセルされる\n- 該当受注の決済がAmazon Pay、LINE Pay、または楽天ペイ（オンライン決済）である場合は、決済金額が自動的に購入者へ返金される\n- 該当受注の決済がPayPay（イプシロン）である場合には、イプシロン側の決済もキャンセルされる\n- ショップポイントがキャンセルされる\n\n販売手数料確定前の場合は以下のことが起こります。\n- 販売手数料が0になる\n- 付与したGMOポイントがキャンセルされる\n- 購入者が使用したGMOポイントがキャンセルされる\n\n現在、以下の機能はサポートしていません。\n- キャンセル連動設定を利用した、クレジット（イプシロン）決済のキャンセル\n- 分割された受注のキャンセル\n",
        "operationId": "cancelSale",
        "tags": [
          "sale"
        ],
        "security": [
          {
            "OAuth2": [
              "write_sales"
            ]
          }
        ]
      }
    },
    "/v1/sales/{sale_id}/mails": {
      "post": {
        "summary": "メールの送信",
        "description": "受注・入金確認・商品発送メールを送ることができます。\n\n対象の受注が分割されている場合、 受注メール、入金確認メールは、親受注でのみ指定可能です。\n",
        "operationId": "sendSalesMail",
        "tags": [
          "sale"
        ],
        "security": [
          {
            "OAuth2": [
              "write_sales"
            ]
          }
        ]
      }
    },
    "/v1/customers": {
      "get": {
        "summary": "顧客データのリストを取得",
        "description": "",
        "operationId": "getCustomers",
        "tags": [
          "customer"
        ],
        "security": [
          {
            "OAuth2": [
              "read_sales"
            ]
          }
        ]
      },
      "post": {
        "summary": "顧客データを追加",
        "description": "",
        "operationId": "postCustomers",
        "tags": [
          "customer"
        ],
        "security": [
          {
            "OAuth2": [
              "write_sales"
            ]
          }
        ]
      }
    },
    "/v1/customers/{customer_id}": {
      "get": {
        "summary": "顧客データの取得",
        "description": "",
        "operationId": "getCustomer",
        "tags": [
          "customer"
        ],
        "security": [
          {
            "OAuth2": [
              "read_sales"
            ]
          }
        ]
      }
    },
    "/v1/customers/{customer_id}/points": {
      "post": {
        "summary": "顧客ショップポイントの増減",
        "description": "`customer_id`で指定した顧客の持つショップポイントに対し`points`リクエストパラメータの数値を加算・減算します。\n\n減算させる場合は`points`リクエストパラメータにマイナス値をセットします。\n",
        "operationId": "postCustomerPoints",
        "tags": [
          "customer"
        ],
        "security": [
          {
            "OAuth2": [
              "write_sales"
            ]
          }
        ]
      }
    },
    "/v1/products": {
      "get": {
        "summary": "商品一覧の取得",
        "description": "商品一覧を取得します。\n\nオプションやバリエーションの数が多い場合、レスポンスの返却に時間がかかる場合があります。 `fields` リクエストパラメータで必要なキーを指定することを推奨します。\n",
        "operationId": "getProducts",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "read_products"
            ]
          }
        ]
      },
      "post": {
        "summary": "商品データの追加",
        "description": "",
        "operationId": "postProducts",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "write_products"
            ]
          }
        ]
      }
    },
    "/v1/products/{product_id}": {
      "get": {
        "summary": "商品データの取得",
        "description": "",
        "operationId": "getProduct",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "read_products"
            ]
          }
        ]
      },
      "put": {
        "summary": "商品データの更新",
        "description": "",
        "operationId": "updateProduct",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "write_products"
            ]
          }
        ]
      }
    },
    "/v1/products/{product_id}/variants": {
      "get": {
        "summary": "商品オプション一覧の取得",
        "description": "",
        "operationId": "getProductVariants",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "read_products"
            ]
          }
        ]
      }
    },
    "/v1/products/{product_id}/pickups": {
      "post": {
        "summary": "おすすめ商品情報の追加",
        "description": "おすすめ商品情報(おすすめ商品、売れ筋商品、新着商品、イチオシ商品のいずれか)を商品に追加します。",
        "operationId": "postProductPickup",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "write_products"
            ]
          }
        ]
      },
      "put": {
        "summary": "おすすめ商品情報の更新",
        "description": "おすすめ商品情報(おすすめ商品、売れ筋商品、新着商品、イチオシ商品のいずれか)を更新します。",
        "operationId": "putProductPickup",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "write_products"
            ]
          }
        ]
      }
    },
    "/v1/products/{product_id}/pickups/{pickup_type}": {
      "delete": {
        "summary": "おすすめ商品情報の削除",
        "description": "商品に付加されたおすすめ商品情報を削除します",
        "operationId": "deleteProductPickup",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "write_products"
            ]
          }
        ]
      }
    },
    "/v1/product_advertisings": {
      "get": {
        "summary": "広告・ショッピング連携設定一覧の取得",
        "description": "商品毎に設定した広告・ショッピング連携設定の内容を取得することができます",
        "operationId": "getProductAdvertisings",
        "tags": [
          "product"
        ],
        "security": [
          {
            "OAuth2": [
              "read_products"
            ]
          }
        ]
      }
    },
    "/v1/stocks": {
      "get": {
        "summary": "在庫情報の取得",
        "description": "在庫情報を商品名や型番で検索できるAPIです。\n",
        "operationId": "getStocks",
        "tags": [
          "stock"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/groups": {
      "get": {
        "summary": "商品グループ一覧を取得",
        "description": "",
        "operationId": "getProductGroups",
        "tags": [
          "group"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/categories": {
      "get": {
        "summary": "商品カテゴリー一覧を取得",
        "description": "",
        "operationId": "getProductCategories",
        "tags": [
          "category"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/payments": {
      "get": {
        "summary": "決済設定の一覧を取得",
        "description": "",
        "operationId": "getPayments",
        "tags": [
          "payment"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/deliveries": {
      "get": {
        "summary": "配送方法一覧を取得",
        "description": "",
        "operationId": "getDeliveries",
        "tags": [
          "delivery"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/deliveries/date": {
      "get": {
        "summary": "配送日時設定を取得",
        "description": "",
        "operationId": "getDeliveryDateSetting",
        "tags": [
          "delivery"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/gift": {
      "get": {
        "summary": "ギフト設定を取得",
        "description": "",
        "operationId": "getGift",
        "tags": [
          "gift"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/v1/shop_coupons": {
      "get": {
        "summary": "ショップクーポン一覧取得",
        "description": "",
        "operationId": "getCoupons",
        "tags": [
          "shop_coupon"
        ],
        "security": [
          {
            "OAuth2": [
              "read_shop_coupons"
            ]
          }
        ]
      }
    },
    "/v1/shop_coupons/{coupon_id}": {
      "get": {
        "summary": "ショップクーポンの取得",
        "description": "",
        "operationId": "getCoupon",
        "tags": [
          "shop_coupon"
        ],
        "security": [
          {
            "OAuth2": [
              "read_shop_coupons"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://api.shop-pro.jp/oauth/authorize",
            "tokenUrl": "https://api.shop-pro.jp/oauth/token",
            "scopes": {
              "read_products": "商品データを参照",
              "write_products": "在庫データを更新",
              "read_sales": "受注・顧客データを参照",
              "write_sales": "受注データを更新",
              "read_shop_coupons": "ショップクーポンを参照"
            }
          }
        }
      }
    }
  }
}
